### PR TITLE
Fix/feature name validation

### LINKED ISSUE #199: [BUG] Feature names not being validated consistently
**Describe the bug**
When entering the command to generate a feature, if the name is included in the command rather than allowing the CLI to prompt you to enter it, the name entered is not being validated. (It's only validated if entered as a response to the CLI's prompt.)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a project using 
```bash 
rdvue create-project test-project
```
2. Enter any command to generate a feature passing a name that doesn't match this regex: `/^[a-zA-Z0-9.\-_]+$/i` like `?`.
```bash
rdvue add:component ?
```
3. Observe that 5 files were added to the components folder (not in their own folder) with the template values not replaced e.g.: `${componentNameKebab}.ts`

```bash
[rdvue] component added: 

  Visit the documentation page for more info:
  https://realdecoy.github.io/rdvue/#/Features?id=components
```

**Expected behaviour**
A printout to the terminal stating: 
```bash
>> Error: Use letters, numbers and '-' for component names (e.g. my-component-name)
```

**Screenshots**
[Resulting files](https://pasteboard.co/4cA7AHXUmhWK.png)

### PR DESCRIPTION
**Pull request by NathanDowner**
I utilized the existing validation function to run the validation on the `argName` variable in the case it was provided.
Closes #199 

**Steps to test**
In an existing rdvue project, enter any command to generate a feature, I'll use the `component` in this case, and besure to include a name that doesn't match the regex: `/^[a-zA-Z0-9.\-_]+$/i`, I'll use`?`.
```bash
rdvue add:component ?
```

**Expected Behaviour**
```bash
    Error:  Use letters, numbers and '-' for component names (e.g. my-component-name)
```

**Actual Behaviour**
```bash
    Error:  Use letters, numbers and '-' for component names (e.g. my-component-name)
```

**Additional Notes**
Should be merged after [PR-198](https://github.com/realdecoy/rdvue/pull/198)

### CODE REVIEW

File: src/lib/utilities.ts [hunk 1]
```diff
@@ -62,145 +62,62 @@ function toPascalCase(value: string): string {
...
-  return isValidArgName ? true : resultMessage;
+function stripRdvuePrefix(value: string): string {
+  return value.replace('[rdvue]', '');
 }
 
 /**
- * Description: determine if string is valid service name
- * @param {string} value - a string value
- * @returns {any} -
+ * Description: Throwsan error with the provided message
```
Comment (andre-vidal) [inline src/lib/utilities.ts:74]: throws an*

**Review by andre-vidal — DISMISSED** [review]
LGTM

File: src/lib/utilities.ts (hunk 1 above)
Comment (NathanDowner) [reply src/lib/utilities.ts]: Thanks for the catch! The fix has been pushed
